name: Approve Me

on:
  issue_comment:
    types: [ "created" ]

jobs:
  approve:
    name: Approve
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, '@github-actions approve me')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Approve pull request
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: gh pr review ${{ github.event.issue.number }} --approve
